language: cpp
compiler: clang
sudo: require
dist: jammy
addons:
  apt:
    packages:
      - cmake
      - libgl1-mesa-dev
      - qt6-base-dev
      - qt6-tools-dev
      - libqt6charts-dev
      - libqt6svg-dev
before_script:
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=release -DCMAKE_CXX_COMPILER=clang++ ..
script:
- make -j $(nproc)
- lupdate ../stacer/stacer.pro -no-obsolete
- lrelease ../stacer/stacer.pro